import {useEffect,useMemo,useState} from "react";
import {validateProfessional,getPatients,createPatient,getPatientHistory,createClinicalRecord,getBlockchainStatus,getBlockchainBlocks,createGenesis,getNodes,createNode,startNode,stopNode,deleteNode} from "../services/api";

const emptyPatient={nombre:"",dui:"",fecha_nacimiento:"",tipo_sangre:"O+",alergias:"",vacunas:"",cronicas:"",telefono:"",direccion:""};
const emptyRecord={motivo_consulta:"",diagnostico:"",tratamiento:"",observaciones:"",signos_vitales:""};
const juntaOptions=["JVPM","JVPP","JVPO","JVPE"];

async function credentials(title="Validación profesional"){
  const {value}=await window.Swal.fire({title,html:`<select id="hc-junta" class="swal2-input"><option value="JVPM">JVPM — Medicina</option><option value="JVPP">JVPP — Psicología</option><option value="JVPO">JVPO — Odontología</option><option value="JVPE">JVPE — Enfermería</option></select><input id="hc-registro" class="swal2-input" placeholder="Ej. JVPM-12345">`,focusConfirm:false,showCancelButton:true,confirmButtonText:"Validar",cancelButtonText:"Cancelar",preConfirm:()=>({tipo_junta:document.getElementById("hc-junta").value,registro_profesional:document.getElementById("hc-registro").value.trim()})});
  if(!value)return null;
  try{const r=await validateProfessional(value); if(r.success){window.Swal.fire({icon:"success",title:"Credenciales válidas",text:r.profesional.nombre,timer:1500,showConfirmButton:false});return {...value,profesional:r.profesional};}}catch(e){window.Swal.fire("Acceso rechazado",e.message,"error");}
  return null;
}
function initials(name="Paciente"){return name.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase()}

export default function SingleDashboard(){
 const [section,setSection]=useState("inicio"),[patients,setPatients]=useState(()=>{try{return JSON.parse(localStorage.getItem("healthchain_patients")||"[]")}catch{return[]}}),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[nodes,setNodes]=useState([]),[blocks,setBlocks]=useState([]),[status,setStatus]=useState(null),[patient,setPatient]=useState(emptyPatient),[record,setRecord]=useState(emptyRecord),[selectedNode,setSelectedNode]=useState(""),[node,setNode]=useState({name:"NODO_1",ip:"127.0.0.1",port:"5001"}),[busy,setBusy]=useState(false);
 const loadPatients=async()=>{try{const r=await getPatients();setPatients(r.pacientes||[])}catch(e){window.Swal.fire("Error",e.message,"error")}};
 const loadNodes=async()=>{try{const r=await getNodes();setNodes(r.nodes||[]);const active=(r.nodes||[]).find(n=>n.running);if(active)setSelectedNode(active.name)}catch(e){window.Swal.fire("Error",e.message,"error")}};
 useEffect(()=>{loadPatients();loadNodes()},[]);
 useEffect(()=>{if(section==="blockchain"){getBlockchainStatus(selectedNode).then(setStatus).catch(()=>{});getBlockchainBlocks(selectedNode).then(r=>setBlocks(r.blocks||[])).catch(()=>{})}},[section,selectedNode]);
 const stats=useMemo(()=>({patients:patients.length,active:nodes.filter(n=>n.running).length,blocks:blocks.length}),[patients,nodes,blocks]);
 async function savePatient(e){e.preventDefault();const c=await credentials("Validar registro de paciente");if(!c)return;setBusy(true);try{const r=await createPatient({...patient,...c});setPatients(x=>[...x,r.paciente]);setPatient(emptyPatient);await window.Swal.fire("Paciente registrado","La ficha fue guardada en pacientes.json. El registro del paciente no genera un bloque.","success");setSection("pacientes")}catch(e){window.Swal.fire("No se pudo registrar",e.message,"error")}finally{setBusy(false)}}
 async function openHistory(p){const c=await credentials("Validar acceso al historial");if(!c)return;try{const r=await getPatientHistory(p.id,c,selectedNode);setSelected(r.paciente);setHistory(r.historial||[]);setSection("historial")}catch(e){window.Swal.fire("No se pudo consultar",e.message,"error")}}
 async function saveRecord(e){e.preventDefault();if(!selected){window.Swal.fire("Selecciona un paciente","Primero selecciona un paciente para registrar la atención.","warning");return}const c=await credentials("Validar registro clínico");if(!c)return;setBusy(true);try{await createClinicalRecord({paciente_id:selected.id,categoria:"CONSULTA",datos:record,...c,node:selectedNode});setRecord(emptyRecord);await window.Swal.fire("Registro creado","La atención clínica fue minada y agregada a la Blockchain.","success");setSection("historial");await openHistory(selected)}catch(e){window.Swal.fire("No se pudo registrar",e.message,"error")}finally{setBusy(false)}}
 async function addNode(e){e.preventDefault();try{await createNode(node);setNode({name:"",ip:"127.0.0.1",port:""});loadNodes();window.Swal.fire("Nodo creado","El nodo quedó registrado.","success")}catch(e){window.Swal.fire("Error",e.message,"error")}}
 async function genesis(){try{const r=await createGenesis(4,"0",selectedNode);window.Swal.fire(r.success?"Blockchain lista":"No se pudo inicializar",r.message,r.success?"success":"error");if(r.success)setSection("blockchain")}catch(e){window.Swal.fire("Error",e.message,"error")}}
 const nav=["inicio","pacientes","historial","registro","blockchain","red"];
 return <div className="app"><aside><div className="brand"><div className="brand-mark">M10+</div><div><b>MESSI HealthChain</b><small>Historia clínica digital</small></div></div><div className="doctor-card"><div className="avatar">DR</div><div><b>Profesional de salud</b><small>Acceso integral del sistema</small></div></div><nav>{nav.map(x=><button className={section===x?"active":""} onClick={()=>setSection(x)} key={x}>{({inicio:"⌂",pacientes:"♙",historial:"◷",registro:"＋",blockchain:"◈",red:"⌁"})[x]} {({inicio:"Inicio",pacientes:"Pacientes",historial:"Historial",registro:"Registrar atención",blockchain:"Blockchain",red:"Red de nodos"})[x]}</button>)}</nav><div className="side-note">Sistema unificado<br/><b>Sin login ni roles</b></div></aside><main><header><div><span>MESSI HEALTHCHAIN</span><h1>{{inicio:"Panel principal",pacientes:"Pacientes",historial:"Historial clínico",registro:"Nueva atención",blockchain:"Blockchain",red:"Red de nodos"}[section]}</h1></div><div className="top-status">● Sistema activo</div></header><section className="content">
 {section==="inicio"&&<><div className="hero"><div><span>GESTIÓN CLÍNICA</span><h2>Todo el sistema en un solo lugar.</h2><p>Administra pacientes, registros clínicos, Blockchain y nodos desde una única interfaz.</p></div><div className="hero-icon">◈</div></div><div className="stats"><div><small>PACIENTES</small><b>{stats.patients}</b></div><div><small>NODOS ACTIVOS</small><b>{stats.active}</b></div><div><small>BLOQUES</small><b>{stats.blocks}</b></div><div><small>VALIDACIÓN</small><b>JVPM / JVPP / JVPO / JVPE</b></div></div><div className="grid2"><div className="card"><h3>Acciones rápidas</h3><div className="quick"><button onClick={()=>setSection("pacientes")}>♙ Gestionar pacientes</button><button onClick={()=>setSection("registro")}>＋ Nueva atención</button><button onClick={()=>setSection("blockchain")}>◈ Ver Blockchain</button></div></div><div className="card"><h3>Protección de operaciones</h3><p className="muted">Las operaciones sensibles solicitan las credenciales profesionales mediante SweetAlert y se validan en el servidor contra profesionales.json.</p></div></div></>}
 {section==="pacientes"&&<><div className="section-head"><div><h2>Pacientes registrados</h2><p>La información actual se conserva en <b>pacientes.json</b>.</p></div><button className="primary" onClick={()=>setSection("registro-paciente")}>＋ Registrar paciente</button></div><div className="patient-grid">{patients.map(p=><div className="patient-card" key={p.id}><div className="avatar big">{initials(p.nombre)}</div><div className="patient-info"><h3>{p.nombre}</h3><span>{p.id} · {p.dui}</span><p>{p.tipo_sangre} · {p.telefono||"Sin teléfono"}</p></div><button className="outline" onClick={()=>openHistory(p)}>Ver historial</button></div>)}</div>{!patients.length&&<div className="empty">No hay pacientes registrados.</div>}</>}
 {section==="registro-paciente"&&<><div className="section-head"><div><h2>Registrar paciente</h2><p>Antes de guardar se validará el registro profesional.</p></div></div><form className="form card" onSubmit={savePatient}><h3>Información del paciente</h3>{Object.entries({nombre:"Nombre completo",dui:"DUI",fecha_nacimiento:"Fecha de nacimiento",tipo_sangre:"Tipo de sangre",alergias:"Alergias",vacunas:"Vacunas",cronicas:"Enfermedades crónicas",telefono:"Teléfono",direccion:"Dirección"}).map(([k,l])=><label key={k}>{l}<input type={k==="fecha_nacimiento"?"date":"text"} value={patient[k]} onChange={e=>setPatient({...patient,[k]:e.target.value})} required={!["telefono","direccion"].includes(k)}/></label>)}<button className="primary full" disabled={busy}>{busy?"Guardando…":"Registrar paciente"}</button></form></>}
 {section==="historial"&&<><div className="section-head"><div><h2>Historial clínico</h2><p>Selecciona un paciente y valida tus credenciales para acceder.</p></div></div><div className="patient-grid">{patients.map(p=><button className="patient-card clickable" key={p.id} onClick={()=>openHistory(p)}><div className="avatar big">{initials(p.nombre)}</div><div className="patient-info"><h3>{p.nombre}</h3><span>{p.id} · {p.dui}</span><p>Consultar historial</p></div></button>)}</div>{selected&&<div className="card history"><div className="profile"><div className="avatar big">{initials(selected.nombre)}</div><div><h2>{selected.nombre}</h2><p>{selected.id} · {selected.tipo_sangre}</p></div></div>{history.map((h,i)=><article key={i}><div><b>{h.categoria||"CONSULTA"}</b><small>{h.timestamp||h.time_stamp||""}</small></div><p><b>Motivo:</b> {h.datos?.motivo_consulta||"Registro de paciente"}</p><p><b>Diagnóstico:</b> {h.datos?.diagnostico||"—"}</p><p><b>Tratamiento:</b> {h.datos?.tratamiento||"—"}</p><p>{h.datos?.observaciones||""}</p><code>{h.block_hash||"Registro de ficha"}</code></article>)}</div>}</>}
 {section==="registro"&&<><div className="section-head"><div><h2>Nueva atención clínica</h2><p>El evento clínico se cifra, mina y queda asociado al paciente.</p></div></div><div className="grid2"><div className="card"><h3>Paciente</h3><select value={selected?.id||""} onChange={e=>setSelected(patients.find(p=>p.id===e.target.value)||null)}><option value="">Seleccionar paciente</option>{patients.map(p=><option key={p.id} value={p.id}>{p.nombre} — {p.id}</option>)}</select></div><form className="form card" onSubmit={saveRecord}>{Object.entries({motivo_consulta:"Motivo de consulta",diagnostico:"Diagnóstico",tratamiento:"Tratamiento",observaciones:"Observaciones",signos_vitales:"Signos vitales"}).map(([k,l])=><label key={k}>{l}<textarea value={record[k]} onChange={e=>setRecord({...record,[k]:e.target.value})} required={k!=="signos_vitales"}/></label>)}<button className="primary full" disabled={busy}>{busy?"Procesando Blockchain…":"Guardar y minar registro"}</button></form></div></>}
 {section==="blockchain"&&<><div className="grid2"><div className="card"><h3>Estado de Blockchain</h3><p className="big-number">{status?.blocks??blocks.length}</p><p className="muted">bloques en el nodo seleccionado</p><button className="primary" onClick={genesis}>Inicializar Genesis</button></div><div className="card"><h3>Nodo activo</h3><select value={selectedNode} onChange={e=>setSelectedNode(e.target.value)}><option value="">Automático</option>{nodes.map(n=><option key={n.name}>{n.name}</option>)}</select><p className="muted">{status?.message||"Consulta el estado del nodo."}</p></div></div><div className="card"><h3>Bloques</h3>{blocks.map((b,i)=><div className="block" key={i}><b>#{b.id}</b><span>{b.hash||b.previous_hash||"—"}</span></div>)}</div></>}
 {section==="red"&&<><div className="grid2"><form className="form card" onSubmit={addNode}><h3>Crear nodo</h3><label>Nombre<input value={node.name} onChange={e=>setNode({...node,name:e.target.value})} required/></label><label>IP<input value={node.ip} onChange={e=>setNode({...node,ip:e.target.value})} required/></label><label>Puerto<input type="number" value={node.port} onChange={e=>setNode({...node,port:e.target.value})} required/></label><button className="primary">Crear nodo</button></form><div className="card"><h3>Nodos</h3>{nodes.map(n=><div className="node" key={n.name}><div><b>{n.name}</b><small>{n.ip}:{n.port} · {n.running?"ACTIVO":"DETENIDO"}</small></div><div className="actions">{n.running?<button onClick={()=>stopNode(n.name).then(loadNodes)}>Detener</button>:<button onClick={()=>startNode(n.name).then(loadNodes)}>Iniciar</button>}<button onClick={()=>deleteNode(n.name).then(loadNodes)}>Eliminar</button></div></div>)}</div></div></>}
 </section></main></div>
}
